name: bmlc_env
channels:
  - defaults
  - rdkit
  - conda-forge
dependencies:
  - numpy
  - pandas
  - python=3.11.7
  - rdkit=2023.9.4
  - scikit-learn
  - scipy
  - seaborn
  - pip:
    - hiplot
    - jupyter
    - optuna
    - pandarallel
    - xgboost
    - git+https://github.com/bp-kelley/descriptastorus
