atompair+donorpair:
    # "parameters" contains a list of dictionaries with featurizer settings.
    # the featurizers must be listed in the same order as the key above.
    parameters: 
          # atompair featurization settings
          - {count: True,
             minDistance: 1,
             maxDistance: 30,
             fpSize: 1024,
             includeChirality: True,
             }

          # donorpair featurization setings
          - {fpSize: 1024}

    save_file_name: atompair_donorpair_2048_count


morgan:
    parameters:
        # morgan parameters
        - {count: True,
           radius: 2,
           fpSize: 2048,
           includeChirality: False,
           }
    
    save_file_name: ECFP4_2048_count

MACCS:
    parameters:
        - {}
    save_file_name: MACCS

