atompair+donorpair:
    # "parameters" contains a list of dictionaries with featurizer settings.
    # the featurizers must be listed in the same order as the key above.
    parameters: 
          # atompair featurization settings
          - {count: True,
             minDistance: 1,
             maxDistance: 30,
             fpSize: 1024,
             includeChirality: True,
             }

          # donorpair featurization setings
          - {fpSize: 1024}

    # filename used to save training results
    save_file_name: atompair_donorpair_2048_count

morgan:
    parameters:
        # morgan parameters
        - {count: True,
           radius: 3,
           fpSize: 2048,
           includeChirality: True,
           }
    
    save_file_name: ECFP6_2048_count

MACCS:
    # there are no settings to specify for generating MACCS Keys
    parameters:
        - {}
    save_file_name: MACCS

MQN:
    # there are no settings to specify for generating MQN Keys
    parameters:
        - {}
    save_file_name: MQN

rdkit_2d_normalized:
    # an empty dictionary indicates the default featurization settings will be used
    parameters:
        - {}
    save_file_name: rdkit_2d_normalized
